apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-secret
  data:
  - secretKey: N8N_ENCRYPTION_KEY
    remoteRef:
      key: kv-v2/data/argocd
      property: N8N_ENCRYPTION_KEY
  - secretKey: "secret.json"
    remoteRef:
      key: kv-v2/data/argocd
      property: "secret.json"
